document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://img.t400.cc/css/service.css\"/>");
document.writeln("<script type=\"text/javascript\" src=\"http://img.t400.cc/js/jquery-1.4.4.min.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"http://img.t400.cc/js/jquery.fixed.1.5.1.js\"></script>");
document.writeln("<script language=\"javascript\">");
document.writeln("//must window loading,don\'t use the document loading");
document.writeln("$(window).load(function(){");
document.writeln("	");
document.writeln("	//悬浮客服");
document.writeln("	$(\"#fixedBox2\").fix({");
document.writeln("		position 		: \"left\",	//悬浮位置 - left或right");
document.writeln("		horizontal  	: 0,		//水平方向的位置 - 默认为数字");
document.writeln("		vertical    	: null,		//垂直方向的位置 - 默认为null");
document.writeln("		halfTop     	: false,	//是否垂直居中位置");
document.writeln("		minStatue 		: false,	//是否最小化");
document.writeln("		hideCloseBtn 	: false,	//是否隐藏关闭按钮");
document.writeln("		skin 			: \"gray\",	//皮肤");
document.writeln("		showBtnWidth 	: 28,       //show_btn_width");
document.writeln("		contentBoxWidth : 154, 		//side_content_width");
document.writeln("		durationTime 	: 600		//完成时间");
document.writeln("	});");
document.writeln("	");
document.writeln("	//悬浮客服");
document.writeln("	$(\"#fixedBox\").fix({");
document.writeln("		position 		: \"right\",	//悬浮位置 - left或right");
document.writeln("		horizontal  	: 0,		//水平方向的位置 - 默认为数字");
document.writeln("		vertical    	: 100,      //垂直方向的位置 - 默认为null");
document.writeln("		halfTop     	: true,	    //是否垂直居中位置");
document.writeln("		minStatue 		: false,	//是否最小化");
document.writeln("		hideCloseBtn 	: false,	//是否隐藏关闭按钮");
document.writeln("		skin 			: \"blue\",	//皮肤");
document.writeln("		showBtnWidth 	: 28,       //show_btn_width");
document.writeln("		contentBoxWidth : 154, 		//side_content_width");
document.writeln("		durationTime 	: 1000		//完成时间");
document.writeln("	});");
document.writeln("	");
document.writeln("});");
document.writeln("</script>");
document.writeln("");
document.writeln("<!-- S 客服 -->");
document.writeln("<div class=\"fixed_box\" id=\"fixedBox\">");
document.writeln("    <div class=\"content_box\">");
document.writeln("        <div class=\"content_inner\">");
document.writeln("        	<div class=\"close_btn\"><a title=\"关闭\"><span>关闭</span></a></div>");
document.writeln("            <div class=\"content_title\"><span>客服中心</span></div>");
document.writeln("            <div class=\"content_list\">            	");
document.writeln("                <div class=\"qqserver\">");
document.writeln("                    <p>                              ");
document.writeln("                        <a target=\"_blank\" href=\"tencent://message/?uin=713050900&Site=T400.CC&Menu=yes\">");
document.writeln("                          <img border=\"0\" src=\"http://wpa.qq.com/pa?p=2:713050900:41\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\">");
document.writeln("                          <span>小路</span>");
document.writeln("                    	</a>");
document.writeln("                    </p>");
document.writeln("                    <p>");
document.writeln("                        <a target=\"_blank\" href=\"tencent://message/?uin=713050907&Site=T400.CC&Menu=yes\">");
document.writeln("                          <img border=\"0\" src=\"http://wpa.qq.com/pa?p=2:713050907:41\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\">");
document.writeln("                          <span>小虹</span>");
document.writeln("                    	</a>");
document.writeln("                    </p>");
document.writeln("                    <p>");
document.writeln("                        <a target=\"_blank\" href=\"tencent://message/?uin=713050902&Site=T400.CC&Menu=yes\">");
document.writeln("                          <img border=\"0\" src=\"http://wpa.qq.com/pa?p=2:713050902:41\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\">");
document.writeln("                          <span>小亚</span>");
document.writeln("                    	</a>");
document.writeln("                    </p>       ");
document.writeln("                    <p>                        ");
document.writeln("                        <a target=\"_blank\" href=\"tencent://message/?uin=713050909&Site=T400.CC&Menu=yes\">");
document.writeln("                          <img border=\"0\" src=\"http://wpa.qq.com/pa?p=2:713050909:41\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\">");
document.writeln("                          <span>老秦</span>");
document.writeln("                    	</a>");
document.writeln("                    </p>");
document.writeln("                                 ");
document.writeln("                </div>               ");
document.writeln("                <hr>");
document.writeln("                <div class=\"phoneserver\">");
document.writeln("                    <h5>客户服务热线</h5>");
document.writeln("                    <p>400-999-0004</p>");
document.writeln("                </div>");
document.writeln("                <hr>");
document.writeln("                <div class=\"msgserver\">");
document.writeln("                    <p><a href=\"http://www.shunking.cn/\">舜王科技官网</a></p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\"content_bottom\"></div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"show_btn\"><span>展开客服</span></div>");
document.writeln("</div>");
document.writeln("<!-- E 客服 -->");
document.writeln("");